"""
Django settings for pagina project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from audioop import reverse
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#yni!3%=3jq8lsb8xf57-_4&rbkilr2_d60bpe3i2dt%nsfq0!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"] # Permitir que todos os hosts possam acessar o site


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app', #agrega app al proyeto
    'rest_framework', #agrega rest_framework al proyecto para que funcione el api rest
]

MIDDLEWARE = [ #agrega middleware al proyecto para que funcione el api rest y el login de django en el proyecto 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pagina.urls'

SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__)) #obtiene la ruta absoluta del archivo de config

#configurar carpeta static
STATICFILES_DIRS = [ 
    os.path.join(SETTINGS_PATH, 'static'),
]

TEMPLATE_DIRS = ( #configurar carpeta templates
    os.path.join(SETTINGS_PATH, 'templates'),
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pagina.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


#conexion a mysql
DATABASES = { 
    'default': {
        'ENGINE': 'django.db.backends.mysql',#driver de mysql
        'NAME': 'shop', #nombre de la base de datos
        'USER': 'django', #usuario de la base de datos
        'PASSWORD': 'django', #contraseña del usuario
        'HOST': 'localhost', #ip del servidor de la base de datos
        'PORT': '3306', #puerto de la base de datos
    }
}

#config media 
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

#evitar que se cierre la sesion al cerrar la ventana
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# evitar que la sesion se cierre al cerrar con el tiempo
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
# evitar que la sesion se cierre al cerrar la ventana
SESSION_SAVE_EVERY_REQUEST = True
AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend',)

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.innovatecsoftware.cl'
EMAIL_HOST_USER = 'hellotama@innovatecsoftware.cl'
EMAIL_HOST_PASSWORD = 'cA6f5%fl(h~A'
EMAIL_PORT = 26
