# Generated by Django 4.0.4 on 2022-06-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_categoria_descripcion_remove_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.IntegerField(default=0),
        ),
    ]
