# Generated by Django 4.0.4 on 2022-07-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_suscrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='tarjeta',
        ),
        migrations.DeleteModel(
            name='TARJETA',
        ),
    ]
