# Generated by Django 4.0.4 on 2022-07-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_compra_tarjeta_delete_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='compra',
            name='tarjeta',
            field=models.CharField(default='', max_length=200),
        ),
    ]
